# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: |
        go install github.com/charmbracelet/bubbletea@latest \
        go install github.com/charmbracelet/bubbles/list@latest \
        go install github.com/charmbracelet/lipgloss@latest \
        go install github.com/charmbracelet/bubbles/textinput@latest \
        go install gopkg.in/yaml.v3@latest

    - name: Build
      run: go build -v -o ld-launch

    #- name: Test
      #run: go test -v ./...
