name: Go Build, Test, and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: darwin
            arch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.11'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Standard Linting
      run: |
        go fmt ./...
        go vet ./...

    - name: Run Tests
      run: go test -v ./...

    - name: Build Binary
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        BINARY_NAME=ld-launch-${{ matrix.os }}-${{ matrix.arch }}
        go build -v -o $BINARY_NAME .
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ld-launch-${{ matrix.os }}-${{ matrix.arch }}
        path: ld-launch-${{ matrix.os }}-${{ matrix.arch }}

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        pattern: ld-launch-*
        merge-multiple: true

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: 0.1.${{ github.run_number }}
        name: Release 0.1.${{ github.run_number }}
        generate_release_notes: true
        files: ./artifacts/ld
        -launch-*
